workspace: "post-cli-example"
variables: 
  base_url: "http://local.hws-console.com"


request: 
  test1: 
    headers: 
      Authorization: 'Bearer MCLvUCICh1zQ1cOYKmrSOy6jqq6sPmnbUWtdJ3ec'
    method: "POST"
    url: "{{base_url}}/ai/:service/:version"
    params: 
      service: 'im'
      version: 'v2'
