workspace: "post-cli-example"
variables: 
  base_url: "http://local.hws-console.com"
  token_image: 'Bearer MCLvUCICh1zQ1cOYKmrSOy6jqq6sPmnbUWtdJ3ec'


request: 
  test1: 
    descriptions: "name of test 1"
    headers: 
      Authorization: "{{token_image}}"
    method: "POST"
    url: "{{base_url}}/ai/:service/:version"
    params: 
      service: 'im'
      version: 'v2'
    data: 
      image: './workspace/Guns-and-stuff.webp'

  test2: 
    descriptions: "name of test 2"
    headers: 
      Authorization: '{{token_image}}'
    method: "POST"
    url: "{{base_url}}/ai/:service"
    params: 
      service: 'image'
    data: 
      image: './workspace/Guns-and-stuff.webp'
      version: '2'

  test3:
    method: "GET"
    params: 
      service: 'image'
